### ISSUE TITLE
struct-valued fields not serializing

### ISSUE THREAD

**Issue by gdamore** [glycerine/zebrapack#10]
Given this:

```
cat ztypes.go
//go:generate zebrapack
// Generic schema.
package rpc

import zebra "github.com/glycerine/zebrapack/msgp"

type ZRequest struct {
	ID		uint64		`zid:"0"`
	Context		zebra.Raw 	`zid:"1"`
	Service		uint8		`zid:"2"`
	Method		uint8		`zid:"3"`
	Params		zebra.Raw	`zid:"4"`
}

type ZError struct {
	Code		int		`zid:"0"`
	Message		string		`zid:"1"`
	Data		zebra.Raw	`zid:"2"`
}

type ZResponse struct {
	ID		uint64		`zid:"0"`
	Context		zebra.Raw	`zid:"1"`
	Error		ZError		`zid:"2"`
	Result		zebra.Raw	`zid:"3"`
}
```

After running go generate and then go test ., we see a failure.

```
--- FAIL: TestMarshalUnmarshalZResponse (0.00s)
    ztypes_gen_test.go:246: msgp: attempted to decode type "map" with method for "int"
--- FAIL: TestEncodeDecodeZResponse (0.00s)
    ztypes_gen_test.go:309: msgp: attempted to decode type "map" with method for "int"
    ztypes_gen_test.go:316: EOF
FAIL
FAIL	_/Volumes/RackTop/RackTop/svc-example	0.007s
```

**Comment by gdamore** [comment]
It seems that zebrapack cannot handle the Raw type -- which is really unfortunate, as I need the ability to do lazy decoding.

**Comment by glycerine** [comment]
Hi Garrett! Thanks for filing this.

Raw types should be okay. There is a test for Raw here.
https://github.com/glycerine/zebrapack/blob/master/_generated/gen_test.go#L83

I'll look and see what the real problem is...

**Comment by gdamore** [comment]
Ok, thanks.

**Comment by glycerine** [comment]
update: not solved, but there is a quick workaround.

Here is a minimized reproducer:
~~~
type ZError struct {
    Context int `zid:"0"`
}

type ZResponse struct {
    Error ZError `zid:"0"`
}
~~~
changing the Error field from a value to a pointer works around the issue:
~~~
type ZError struct {
    Context int `zid:"0"`
}

type ZResponse struct {
    Error *ZError `zid:"0"`
}
~~~

**Comment by gdamore** [comment]
So the team really wants to use this.  But this bug is getting in the way... I'll see if I can figure this out.  I note that raw fields do work fine, it seems to be the struct fields that are problem indeed.

**Comment by gdamore** [comment]
Also, one of my examples generated this: []uint8 len: 25, cap: 103, [132,255,168,82,101,115,112,111,110,115,101,1,192,130,255,165,69,114,114,111,114,2,192,3,192]

The interesting thing about this is that we have a four element fixmap but the first item appears to be -1 as the map key.  Something is not happy . -- seems like it is on the marshal side.

**Comment by gdamore** [comment]
So more.  Given minimal:

```
//go:generate zebrapack
// Generic schema.
package repro

type Inner struct {
	ID int `zid:"0"`
}

type Outer struct {
	In Inner `zid:"0"`
}
```

Marshal of a zero valued Outer gives:

```
[]uint8 len: 16, cap: 28, [130,255,165,79,117,116,101,114,129,255,165,73,110,110,101,114]
```

If Inner is changed to a pointer, then we get this:

```
[]uint8 len: 8, cap: 11, [129,255,165,79,117,116,101,114]
```

**Comment by gdamore** [comment]
Oh, and the pointer works.  I'm struggling to understand what that leading 255 is... it looks like it should be fixint -1 ?

**Comment by gdamore** [comment]
Ok, I get it now... the -1 encodes the name of the enclosing type, Outer.  Cute.

**Comment by gdamore** [comment]
Eyeballing this it looks like the first encoding encodes an object name Inner, with no members.  So the ID is missing.

**Comment by glycerine** [comment]
Since greenpack works for struct fields, it might be useful as a positive control.

Just a guess: see if putting a non-zero-value into ID makes a difference?

**Comment by gdamore** [comment]
Without structnames-on-wire we get something a little easier, but still wrong:
```
[]uint8 len: 2, cap: 17, [129,128]
```
This should be a fixmap of just one element (129),  but 128 is not enough -- 128 is an empty fixmap.  So what is encoded on the wire has no keys no, is just a  map with the single key (no value) which itself is an empty map.

And now looking at the first encoding, I can clearly see that we're failing to encode the zid (0).

**Comment by glycerine** [comment]
> Ok, I get it now... the -1 encodes the name of the enclosing type, Outer. Cute.

Yep. Some way was needed to identify the type.

**Comment by gdamore** [comment]
So what I think *should* have been coded instead for that trivial example is:

```
[ 129, 0, 129, 0, 0 ]
```

Meaning I think we're missing that 0 for the ZIDs (as well as the value).

Possibly something is trying to optimize away zero?

**Comment by glycerine** [comment]
> Possibly something is trying to optimize away zero?

Quite possibly, yes.

**Comment by gdamore** [comment]
Interesting this is utterly busted.

```
type Inner struct {
	ID int `zid:"0",omitempty`
	X int `zid:"1"`
}

type Outer struct {
	In Inner `zid:"0"`
}
```

This was an attempt to force a non-zero ZID.

The result was also

```
[]uint8 len: 2, cap: 17, [129,128]
```

I think I need to deep dive into the marshalling to figure it out.

**Comment by gdamore** [comment]
Reading generated code is *soo* much fun.  👎

**Comment by gdamore** [comment]
The JSON scheme looks ok...

**Comment by glycerine** [comment]
look at the fieldsNotEmpty() methods that are generated. I think it is returning 0 when it should return 1.

**Comment by gdamore** [comment]
I'm looking at that right now.

```
	if !empty[0] {
		// zid 0 for "In"

		// honor the omitempty tags
		var empty [2]bool
		fieldsInUse := z.In.fieldsNotEmpty(empty[:])
		o = msgp.AppendMapHeader(o, fieldsInUse)

		if !empty[0] {
			// zid 0 for "ID"
			o = append(o, 0x0, 0x0)
			o = msgp.AppendInt(o, z.In.ID)
		}

		if !empty[1] {
			// zid 1 for "X"
			o = append(o, 0x1)
			o = msgp.AppendInt(o, z.In.X)
		}

	}
```

**Comment by gdamore** [comment]
It looks like this elides zid 0?  

```
	var fieldsInUse uint32 = 2
	isempty[0] = (z.ID == 0) // number, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (z.X == 0) // number, omitempty
	if isempty[1] {
		fieldsInUse--
	}
```

**Comment by gdamore** [comment]
Oh wait, thats my ID...

**Comment by glycerine** [comment]
yeah.

**Comment by gdamore** [comment]
I should have chosen a better name for debug lol.

**Comment by gdamore** [comment]
Why is it optimizing away these -- I didn't specify omit empty except for the ID field...

**Comment by glycerine** [comment]
from the comment, it looks to be doing it for all numbers.

After reading one the use cases for flatbuffers (having a struct represent a game monster that may have 100 attributes most of which are almost always zero), it seemed reasonable to omit zero-valued fields on the wire. After all, the same zero-ing logic will apply if you introduce a new version of the struct with field unknown to older client code.

**Comment by gdamore** [comment]
I would have expected that to be done only if I requested it do so ... via omitempty.

**Comment by gdamore** [comment]
(There are cases where 0 is definitely *not* the same as not present... the fact that go treats zero values as zero is specific to go, and will depend on decoders after all.)

**Comment by glycerine** [comment]
> (There are cases where 0 is definitely not the same as not present... the fact that go treats zero values as zero is specific to go, and will depend on decoders after all.)

Distinguishing between zero and not-present in general requires keeping a separate bitmap of present or not present for each field. Most of the time that bitmap space is wasted. So we chose not to model that.

**Comment by gdamore** [comment]
Understood, and I understand why your unmarshaller could choose that, although I would prefer to have an error returned if a "required" field was missing, much like the JSON decoders do.  (I.e. leave this choice to the user.)

**Comment by glycerine** [comment]
Most people's experience with protobufs has put them off of required fields. That is, "required" are generally talked about as a misfeature that prevents protocol evolution. Depends on use case, of course.

**Comment by glycerine** [comment]
by the way, have you looked at flatbuffers? Might be more mature and give you similar performance and/or C bindings already? https://google.github.io/flatbuffers/

**Comment by gdamore** [comment]
I have not, but maybe I should.

**Comment by glycerine** [comment]
My only reservation with flatbuffers was I couldn't see how they could ever encode a struct containing two arrays with more than 2^16 elements. Seemed designed only for small data.

**Comment by glycerine** [comment]
Oh and the bitmaps for present/not-present... I think I tried to implement them and then couldn't get the pull request accepted. Or vice-versa. Its been a couple of years.

**Comment by glycerine** [comment]
not sure if somebody else ever took this up... https://github.com/google/flatbuffers/pull/3332

**Comment by gdamore** [comment]
looking briefly... for my team we all work in Go, and a subset of us in C.  We go back and forth to JSON.   So messagePack is definitely preferred -- and having the schema/IDL be in Go itself is a big win.  If we can make Zebrapack do what we want (fix the bugs?) it seems like the best of all worlds.

**Comment by glycerine** [comment]
I'm happy to have you pick up the zebrapack banner and use it. I don't have a much time to debug but I can certainly help some.

**Comment by glycerine** [comment]
If you need/ want to add the present/not-present bitmaps, I did the Go version of roaring's bitmaps. They are pretty space efficient.

https://github.com/RoaringBitmap/roaring

**Comment by gdamore** [comment]
It looks like this is where the problem is in the generated code:

```
	if !empty_zgensym_5b4ac13e07523495_10[0] {
		// zid 0 for "In"

		// honor the omitempty tags
		var empty_zgensym_5b4ac13e07523495_12 [2]bool
		fieldsInUse_zgensym_5b4ac13e07523495_13 := z.In.fieldsNotEmpty(empty_zgensym_5b4ac13e07523495_12[:])
```

Note that comment "zid for "In" ... but then we write the map header but don't write the ZID!!!

**Comment by glycerine** [comment]
Arg. Not good.

I think the encode generating code is here

https://github.com/glycerine/zebrapack/blob/master/gen/encode.go#L116

**Comment by glycerine** [comment]
and the parallel code in greenpack where it works...

https://github.com/glycerine/greenpack/blob/master/gen/encode.go#L116

**Comment by gdamore** [comment]
So I was able to make two small changes... to the generated code to fix it.

Adding an en.Append(0) after the ZID,

and changing the code which read:

```
			// zid 0 for "ID"
			err = en.Append(0x0, 0x0)
```

to just

```
     err = en.Append(0)
```

I think there is a problem with how stuff is getting pushed on the stack you're using for this, where the ZID is somehow getting pushed into the following map write.

**Comment by gdamore** [comment]
I suspect a missing a call to fuseHook.

**Comment by glycerine** [comment]
might also have to do with the inliner. Test by making the struct very big and then it won't get inlined.

**Comment by gdamore** [comment]
Well the fuseHook change wasn't the fix apparently?  Except maybe... there may be more than one of these.

**Comment by glycerine** [comment]
Its the inliner. If make Inner so big it doesn't get inlined, then it works.

~~~
package main

//go:generate greenpack

type Inner struct {
	ID int `zid:"0",omitempty`
	X  int `zid:"1"`

	B string `zid:"2"`
	C string `zid:"3"`
	D string `zid:"4"`
	E string `zid:"5"`
	F string `zid:"6"`
	G string `zid:"7"`
	H string `zid:"8"`
	I string `zid:"9"`
}

type Outer struct {
	In Inner `zid:"0"`
}

func main() {}
~~~

**Comment by gdamore** [comment]
What's controlling the inlining?

**Comment by glycerine** [comment]
> What's controlling the inlining?

search for Complexity() functions

**Comment by gdamore** [comment]
I think I just fixed it.

**Comment by gdamore** [comment]
*yes*.

**Comment by gdamore** [comment]
```
diff --git a/gen/encode.go b/gen/encode.go
index 18b8cd2..b336174 100644
--- a/gen/encode.go
+++ b/gen/encode.go
@@ -184,6 +184,7 @@ func (e *encodeGen) structmap(s *Struct) {
                        e.p.printf("\n// write %q", s.Fields[i].FieldTag)
                }
                e.Fuse(data)
+               e.fuseHook()
                next(e, s.Fields[i].FieldElem)

                if fast || (s.hasOmitEmptyTags && s.Fields[i].OmitEmpty) {
diff --git a/gen/marshal.go b/gen/marshal.go
index 1020ef6..ceed5a6 100644
--- a/gen/marshal.go
+++ b/gen/marshal.go
@@ -175,6 +175,7 @@ func (m *marshalGen) mapstruct(s *Struct) {
                        m.p.printf("\n// string %q", s.Fields[i].FieldTag)
                }
                m.Fuse(data)
+               m.fuseHook()
                next(m, s.Fields[i].FieldElem)

                if fast || (s.hasOmitEmptyTags && s.Fields[i].OmitEmpty) {
```

**Comment by gdamore** [comment]
Want a PR for this?

**Comment by glycerine** [comment]
Just pushed it.

**Comment by gdamore** [comment]
Guess not LOL. :)

**Comment by gdamore** [comment]
And thank you btw.

**Comment by glycerine** [comment]
You're welcome. Glad it was a quick fix.
